### ISSUE TITLE
Scroll view content offset reset

### ISSUE THREAD

**Issue by shabib87** [shabib87/SHViewPager#1]
When a UIViewController is pushed over the UIViewController that has the SHViewPager, on popping that top UIViewController the content offset of the scroll view of the SHViewPager is reset to zero (0) regardless of the last position of the content offset.

**Comment by ksandyasa** [comment]
Hello, the bug can be fixed if the UIViewController that has the SHViewPager, call the method [self.viewPager pagerWillLayoutSubviews]; called in - (void)viewWillAppear:(BOOL)animated.
In addition, i created method of -(void)moveToTargetIndexWithoutAnimation in SHViewPager.m, duplicate method of moveToTargetIndex but without animation. 
And the result, when a UIViewController is pushed over the UIViewController that has the SHViewPager,
on popping that top UIViewController the content offset of the scroll view of the SHViewPager back to the last position of the content offset.

**Comment by ksandyasa** [comment]
Anyway, your project library really helps me out, thanks a lot for creating this awesome viewpager for ios!

**Comment by shabib87** [comment]
@ksandyasa , thank you! Could you please create a pull to merge request so that this solution can be merged with the master brunch?

**Comment by ksandyasa** [comment]
I can't push to master branch because i don't have permission to push it aka permission denied..

**Comment by shabib87** [comment]
Please fork the source, make the changes and then commit. After that you'll be able to make a pull to merge request.
