### ISSUE TITLE
Position of page menu

### ISSUE THREAD

**Issue by ghost** [shabib87/SHViewPager#29]
Is it possible to modify the page menu's position? Right now it is anchored at the top of the view but I'd rather see it below the viewpager.

**Comment by shabib87** [comment]
Yes, but you need to make changes in the library classes (SHViewPager.m and SHViewPager.xib). Right now I don't have any plans to change the position of the top view. You're always welcome to make the changes at your end and if you can automate it I shall be more than happy to accept the merge request.
Thanks!
