### ISSUE TITLE
Is there a way to use it with React Native?

### ISSUE THREAD

**Issue by azeemhassni** [shabib87/SHViewPager#30]
I understand this is only for iOS, but can we bring it to JavaScript as React Native component only for iOS because Android natively supports top tabs.

This will help us to have more performance than the JS implementations out there.

I've seen the JS implementations are really bad when it comes to performance with lots of data.

**Comment by imdadshafi** [comment]
+1

**Comment by shabib87** [comment]
Right now there is no plan to support react native. But anyone is more than welcome to do so.
