### ISSUE TITLE
Screen rotation

### ISSUE THREAD

**Issue by Reapert** [shabib87/SHViewPager#5]
Hey;

Can you please tell me how to support rotating? When I rotate the screen from portrait to landscape, the size of the pager doesn't change and sticking to the left side of the screen.

Portrait:

![screen shot 2014-09-16 at 11 09 09](https://cloud.githubusercontent.com/assets/6643505/4284164/e276e8cc-3d78-11e4-8fed-3631f7e18ab1.png)

Landscape

![screen shot 2014-09-16 at 11 09 24](https://cloud.githubusercontent.com/assets/6643505/4284169/f97a5f86-3d78-11e4-81bc-d12bbb0dd8d2.png)

Thanks

**Comment by Anhnh** [comment]
@Reapert : I have same issue with you. Did you find any solution for this issue?
